/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "tprhkqoiomnojudkwyut"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRwcmhrcW9pb21ub2p1ZGt3eXV0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQzNjc1MjYsImV4cCI6MjA3OTk0MzUyNn0.xLAs9CZkcd-FHJlT7-_oSXZ5_n7_U9Yqiw4M7PDRVPc"